"""empty message

Revision ID: edb1bf16974d
Revises: 63b086a1c97b
Create Date: 2022-04-13 18:13:21.303858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb1bf16974d'
down_revision = '63b086a1c97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('code_block', sa.String(length=250), nullable=True),
    sa.Column('explanation', sa.String(length=250), nullable=True),
    sa.Column('do_good', sa.String(length=250), nullable=True),
    sa.Column('do_bad', sa.String(length=250), nullable=True),
    sa.Column('do_next', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
